### ISSUE TITLE
Breaking 1 Light Connector Breaks all Lights Directly Next To It

### ISSUE THREAD

**Issue by Darkosto** [pau101/Fairy-Lights#12]
Hello!

When building many fairly lights, and the connectors are placed directly next to each other, breaking 1 connector will break all touching connectors. This would be a tough thing to have happen after building a large set of lights :P 

Thank you! 
Darkosto

**Comment by pau101** [comment]
I'm unable to reproduce the issue, as you were after a certain number of times. This surely must be some compatibility issue. It is impossible for what happened in stream to happen with this mod alone.

<p align="center"><img src="http://i.imgur.com/NgyvQmi.gif" alt="GIF of bug during Stream" width="75%"></p>

I find this particularly bizarre because the fastener block doesn't expose the items that will be dropped to enable a mod to know what would be dropped, they're just spawned in as entities manually.

For all the items of the connections to spawn after they have all appeared to have disconnected in the block which the broken fastener was on requires a mod to capture spawned item entities during the block being broken and respawn them in a different location.

**Comment by pau101** [comment]
So what I suspected is exactly what OreExcavation is doing, you must have had that enabled when breaking some of the fasteners.
