### ISSUE TITLE
Dark spot despite having fairy lights

### ISSUE THREAD

**Issue by Ricket** [pau101/Fairy-Lights#25]
I'm not sure what's going on here, there's a random dark spot where I put fairy lights. It was not dark last I checked.

![image](https://user-images.githubusercontent.com/196978/28648426-c4cb38b4-723b-11e7-8b44-5126b02a22a1.png)

fairylights-2.1.0-1.11.2.jar

After taking the screenshot and writing this, I looked back and it was lit up...

![image](https://user-images.githubusercontent.com/196978/28648468-0c43960a-723c-11e7-85b2-a4190f2aee52.png)

Is this a feature, like are the lights supposed to randomly "burn out" or something?

**Comment by pau101** [comment]
This is expected, although not ideal behavior, the game performs periodic light checks around players so blocks may become unlit from the lights working in an unconventional way but will eventually be corrected by the lights.

I'll keep the issue open because I may be able to correct it but it is not high priority.

**Comment by Ricket** [comment]
I mean, I walked in and there was a zombie and a creeper, so I'm definitely thinking I will switch back to torches (which never do this), or make some kind of monster spawn prevention block. I've used other mods' lights before and never had that issue. If it was just cosmetic that's one thing, but for a light to randomly go dark enough for monsters to spawn, that's a fairly serious bug IMO.
