### ISSUE TITLE
ServerEventHandler.onGetCollisionBoxes() has MASSIVE performance issues with particles

### ISSUE THREAD

**Issue by Builderb0y** [pau101/Fairy-Lights#3]
![](http://i.imgur.com/oYjOYzw.png)
Half a stack of netherrack fires was enough to bring my client down to less than 2 FPS. Similar issues also occur with most other particle sources (including modded ones), since most of the particles they spawn call super.onUpdate().

Using version 2.0.0 for MC 1.10.2

**Comment by pau101** [comment]
Doing my own testing shows perfectly fine performance, 4% for `onGetCollisionBoxes`:
![snapshot](https://cloud.githubusercontent.com/assets/5201207/21200850/9df5a81c-c1fd-11e6-80bd-a37f17225fff.png)
I tested with this setup:
![setup](https://cloud.githubusercontent.com/assets/5201207/21200822/83de187e-c1fd-11e6-93ee-02f1a903b961.png)

I'll need your world save so I can test your exact circumstances.

**Comment by Builderb0y** [comment]
I've replicated the issue in a fresh super flat world, so the world itself doesn't seem to be important. I'll test it again with nothing but fairy lights installed, and if the issue vanishes, then I'll try re-adding mods until it shows up again.

**Comment by Builderb0y** [comment]
Several hours of testing later, and I finally found the cause: advanced rocketry's rockets seem to cause particles to lag horribly with fairy lights installed. The issue starts when a rocket entity is spawned on the client, and persists until the client is restarted. Instance folder for testing: https://www.dropbox.com/s/pqthbwsr8hefjgj/Particle%20Lag.zip?dl=0

@zmaster587 Any ideas why this might be happening? I know entities can collide with rockets just like they do with boats, but that alone shouldn't cause issues like this. After all, I was able to spawn at least 100 boats without any issues.

**Comment by zmaster587** [comment]
The only thing I can think of is that AR expands the distance for collide
checks because the largest rockets are bigger than the default max size.
That could cause a massive increase in the amount of collision checks run
if a very large number of entities are between the default col check size
and the modified one.

I'll run some tests on this tmmr and try to confirm my theory.

**Comment by pau101** [comment]
I've determined the cause of this issue. There is a value `World.MAX_ENTITY_RADIUS`, which controls the search size for finding entities within AABBs, by default it is 2. The rocket entity from Advanced Rocketry sets this value to 100 in its onUpdate method, seen [here](https://github.com/zmaster587/AdvancedRocketry/blob/ab82a8b5287c001a9451823fe4d21b67a2914884/src/main/java/zmaster587/advancedRocketry/entity/EntityRocket.java#L498).

I imagine it does this so that the entity can get away with moving really fast and still collide with blocks, but changing `World.MAX_ENTITY_RADIUS` to 100 is not the correct solution.

It results in at least 144, _derived from (⌊100 ÷ 16⌋ × 2)<sup>2</sup>_, chunks needing to be searched for entities any time the client needs to find entities within bounding boxes.

This issue is very apparent with Fairy Lights and many particles because I use an event provided by Forge to make the steps of my step-ladder walkable. It is very easy to produce a lot of particles so for particles it is very apparent but having many of different vanilla things could make the same rocket inefficiency visible.

Looking at my code for the step-ladder collision I should be making the collision only active for entities like how normal entity collision is, e.g. boats have hard collision. So, I can resolve this occurrence of the issue by doing so, but @zmaster587 should alter rocket collision to not increase `World.MAX_ENTITY_RADIUS` to the insane amount to improve overall performance.

**Comment by pau101** [comment]
I've released [2.0.1](https://minecraft.curseforge.com/projects/fairy-lights/files/2356365) which resolves particles causing lag once a rocket has been in the game.
