### ISSUE TITLE
[1.12.2] Odd behaviour when using fairy lights + crafttweakers recipes.replaceAllOccurances

### ISSUE THREAD

**Issue by SeriousCreeper** [pau101/Fairy-Lights#77]
Heya,

i was going to use Fairy Lights in a Betweenlands focused modpack and wanted to replace some of the fairy lights recipe ingredients with others (as well as replace ingredits in other mod recipes). To do that i use crafttweakers `recipes.replaceAllOccurances`. However, i started to notice recipes suddenly behaving really stranged and pin pointed the problem down to fairy lights. 

I can re-create the issue in an instance with just JEI, Fairy Lights, and crafttweaker + the 1 line of script:
`recipes.replaceAllOccurences(<minecraft:iron_ingot>, <minecraft:stick>);` 
(in this example it replaces any iron ingots in a recipe with sticks instead, but i can recreate this with all kinds of replacements)

Here is a video of what's happening: https://streamable.com/vk5xhj 

**Weird behavious include:**
- ingredients suddenly duplicating
- ingredients vanishing when moving around the grid
- output items getting "stuck" (as in, once it shows an output, it won't update properly when inputting a wrong recipe)
- items getting duped when closing the crafting table

Here is my latest.log file too (it shows some errors with CT when trying to crafting something): https://pastebin.com/0dquVtpG 

**Versions used:**
forge - 14.34.5.2854
fairy lights - 2.1.11-1.12.2
JEI - 4.15.0.297
CraftTweaker - 4.1.20.581

Let me know if i can provide anything else that might be helpful!

**Comment by pau101** [comment]
Thanks for reporting!

It looks like that replace function will not work on most of my recipes because they are all dynamic, with the usage of dyes and variable input ingredients. I checked the crafttweaker code and it appears to make an assumption that if a recipe provides an ingredients list it is not dynamic and tries replacing anyway. As well there is inconsistent null handling resulting in errors occurring which are leading to the weird behavior which the log shows too.

Unfortunately there does not appear to be anything I can do, as well I only provide critical bug fixes to 1.12.

**Comment by SeriousCreeper** [comment]
That's unfortunate, but makes sense! Appreciate you taking a look though, and thanks for making an awesome mod!
