### ISSUE TITLE
Crafting recipes are not part of the normal JEI Crafting category

### ISSUE THREAD

**Issue by mezz** [pau101/Fairy-Lights#8]
You can make your custom recipes work as part of the vanilla Crafting recipe category.

Just have your wrapper implement `ICraftingRecipeWrapper` and use `VanillaRecipeCategoryUid.CRAFTING`.
Then you should be able to remove `GenericRecipeCategory` and `GenericRecipeCategory.UID`.

**Comment by pau101** [comment]
The reason I've made the fake crafting category is so I can adjust the displayed inputs to the focus in order to partially allow the recipes to appear correct, but it fails for ingredient usage lookup.

I've been meaning to get it touch to see how my [GenericRecipe](https://github.com/pau101/Fairy-Lights/blob/adb259f0f9f82d708ff4841a34503c6d224853c6/src/main/java/com/pau101/fairylights/util/crafting/GenericRecipe.java) class could be supported fully in JEI.
I created it as a general purpose recipe class to handle recipes which have NBT determined by ingredients or optional ingredients. You can see how I use it for recipes in the [Recipes](https://github.com/pau101/Fairy-Lights/blob/adb259f0f9f82d708ff4841a34503c6d224853c6/src/main/java/com/pau101/fairylights/server/item/crafting/Recipes.java) class.

Any thoughts would be greatly appreciated.

**Comment by mezz** [comment]
Check out the javadocs on `ICustomCraftingRecipeWrapper`, it will let you have control over everything on your crafting recipe in that category.

**Comment by pau101** [comment]
Thank you for your help.
Will mezz/JustEnoughItems@2100e79 be applied to the 1.10.2 branch? Otherwise I can't implement the same full behavior of GenericRecipeHander in both current versions of Fairy Lights.

**Comment by mezz** [comment]
Unfortunately that is a breaking change so it will not get applied to 1.10.2, only 1.11.

**Comment by pau101** [comment]
Alright, thanks again.
